name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Copy files to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST}}
          port: ${{ secrets.SSH_PORT}}
          user: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          scp: |
            ./dist/* => /home/${{ secrets.SSH_USER }}/
